-- Fromage & Figue: starting products. Run AFTER schema.sql. Safe to run again (it resets these rows).
insert into public.categories (id,name,section,sort) values
('soft','Soft','collection',0),
('hard','Hard','collection',1),
('blue','Blue','collection',2),
('pantry','Pantry','collection',3),
('board','Cheese boards','gifts',4),
('box','Gift boxes and hampers','gifts',5),
('voucher','Gift vouchers','gifts',6)
on conflict (id) do update set name=excluded.name, section=excluded.section, sort=excluded.sort;

insert into public.products (id,name,category,note,pair,price,unit,price_from,img,images,origin,milk,age,texture,intensity,notes,story,drink,serve_with,serve,keep,serves,includes,flag,sort) values
('brie','Brie de Meaux','soft','Supple and creamy, with notes of mushroom and cream. Best at room temperature.','A crisp white, warm baguette',9,'100g',false,'brie',array['counter','board']::text[],'Ile-de-France','Cow''s milk','5 to 8 weeks','Soft, bloomy rind',2,array['Mushroom','Fresh cream','Hazelnut']::text[],'The king of cheeses, made on the plains east of Paris for centuries. A thin, velvety white rind gives way to a pale, supple paste that turns glossy and rich as it ripens.','Champagne, or a crisp Chablis','Warm baguette, pears, walnuts','Take it out of the fridge an hour before serving. Cut wedges from the centre so every slice has rind and paste.','Seven to ten days in its paper, in the coolest part of the fridge.','','{}'::text[],'',0),
('reblochon','Reblochon','soft','Washed rind, supple and nutty, with a gentle fruit.','New potatoes, a crisp white',9,'100g',false,'reblochon',array['lunch','tasting']::text[],'Savoie','Cow''s milk','5 to 8 weeks','Soft, washed rind',3,array['Toasted nuts','Cream','Gentle fruit']::text[],'A mountain cheese from the Alps, rubbed with brine as it ages. The golden rind is mild and the paste is supple, with a sweetness the Savoyards guard jealously.','Dry white from Savoie, or a light red','New potatoes, cured ham, crusty bread','Wonderful at room temperature, and the heart of a classic tartiflette when you want something hot.','Five to seven days. Eat the rind if you like it, or leave it.','','{}'::text[],'',1),
('comte','Comté 24 months','hard','Nutty and caramel sweet, with fine crystals and a long finish.','Walnut bread, a glass of white',8,'100g',false,'comte',array['board','counter']::text[],'Jura','Raw cow''s milk','24 months','Firm, with fine crystals',3,array['Caramel','Roasted nuts','Brown butter']::text[],'Made in village cooperatives in the Jura mountains from the milk of a single herd. Twenty-four months in the cellar gives a deep amber paste and the crunchy crystals that Comte lovers look for.','Vin jaune, or a rich white Burgundy','Walnut bread, apple, dried apricot','Cut thin slices and let them warm for a few minutes. Shave over soup or eggs for a savoury finish.','Two to three weeks, wrapped and kept in the fridge.','','{}'::text[],'',2),
('roquefort','Roquefort','blue','Bold and salty over a creamy blue. Superb with honey.','Honey, walnuts, a sweet wine',10,'100g',false,'roquefort',array['tasting','board']::text[],'Aveyron','Sheep''s milk','At least 3 months','Creamy, veined blue',5,array['Salt','Cream','Peppery spice']::text[],'Ripened in the natural limestone caves of Combalou, where cool damp air carries the blue mould through the curd. Bold, salty and surprisingly creamy.','Sauternes, or a sweet Muscat','Honey, walnuts, dark rye bread','Crumble over a salad, melt into a sauce, or serve alone with something sweet to meet the salt.','One to two weeks. Wrap it well, as its aroma carries.','','{}'::text[],'',3),
('goat','Fresh goat cheese','soft','Bright and lemony, with a delicate, soft texture.','Warm bread, olive oil',7,'100g',false,'goat',array['lunch','counter']::text[],'Loire Valley','Goat''s milk','A few days','Fresh and soft',1,array['Lemon','Fresh cream','Grass']::text[],'A fresh goat cheese with a soft, fine curd and a clean, bright tang. It is at its best in the days after it is made.','Sancerre, or a dry cider','Warm bread, olive oil, fresh herbs','Spread on warm toast with a little olive oil and black pepper, or crumble over roast vegetables.','Four to five days in the fridge. Eat it soon.','','{}'::text[],'',4),
('manchego','Manchego','hard','Buttery sheep''s milk cheese from La Mancha, with a gentle nuttiness.','Quince, almonds, dry sherry',7,'100g',false,'manchego',array['board','shelves']::text[],'La Mancha, Spain','Sheep''s milk','6 months','Firm and buttery',3,array['Toasted almond','Butter','Sweet grass']::text[],'Made from the milk of Manchega sheep on the high plains of central Spain. The pale, buttery paste carries a gentle nuttiness and a clean, lingering finish.','Dry sherry, or a young Rioja','Quince paste, almonds, cured chorizo','Cut in thin wedges and serve at room temperature with something sweet beside it.','Three to four weeks wrapped in the fridge.','','{}'::text[],'',5),
('gorgonzola','Gorgonzola Dolce','blue','Mild, spoonable and rich.','Pears, toasted bread',8,'100g',false,'gorgonzola',array['tasting','counter']::text[],'Lombardy, Italy','Cow''s milk','About 2 months','Soft, creamy blue',3,array['Cream','Sweet and tangy','Mild blue']::text[],'The mild, young style of Gorgonzola. Soft enough to spoon, with a gentle blue note and a sweet, milky finish that wins over people who think they do not like blue cheese.','Moscato d''Asti, or a light red','Pears, toasted bread, honey','Spread on warm bread, stir into risotto at the end, or serve with ripe pear.','One to two weeks, wrapped in the fridge.','','{}'::text[],'',6),
('camembert','Camembert de Normandie','soft','Rich and earthy, with a melting centre. Excellent baked.','Warm baguette, cider',8,'piece',false,'camembert',array['camembert','lunch']::text[],'Normandy','Cow''s milk','3 to 4 weeks','Soft, bloomy rind',3,array['Earthy','Buttery','Mushroom']::text[],'Rich and earthy, with a rind that sets it apart from its cousin Brie. The centre melts as it ripens. A natural for baking whole.','Normandy cider, or a light red','Warm baguette, rosemary, honey','Score the top, tuck in rosemary and a thread of honey, and bake for about twenty minutes until molten.','One week. Bring to room temperature before serving.','','{}'::text[],'',7),
('bread','Walnut bread','pantry','Baked daily, an excellent partner for blue cheese.','Blue cheese, honey',6,'loaf',false,'bread',array['lunch','shelves']::text[],'Baked daily','Contains gluten, walnuts','Fresh each day','Crusty, with a soft crumb',1,array['Toasted walnut','Wheat','Sourdough tang']::text[],'A loaf studded with walnuts, baked fresh every morning. The nuts and the gentle sourness make it the partner that blue cheese was waiting for.','Anything you are serving with the cheese','Roquefort, Gorgonzola, honey','Slice it thick and toast it lightly just before serving.','Best on the day. Freezes well sliced.','','{}'::text[],'',8),
('figs','Fresh figs','pantry','Seasonal, and picked ripe.','Any cheese in the collection',6,'box',false,'figs',array['board','tasting']::text[],'Seasonal','Fruit, picked ripe','In season','Soft and juicy',1,array['Honey','Berry','Soft sweetness']::text[],'Ripe figs, picked at the right moment and boxed with care. They are the classic partner for almost every cheese on the counter.','A glass of something sparkling','Soft cheeses, blue cheese, ham','Halve and serve alongside the cheese, or roast for ten minutes with a little honey.','Two to three days. Eat them soon.','','{}'::text[],'',9),
('jam','Fig jam','pantry','Small batch, slowly cooked.','Comté, brie, goat cheese',9,'jar',false,'jam',array['shelves','giftbox']::text[],'Small batch','Fruit and sugar','Shelf stable','Thick and glossy',1,array['Dark fruit','Honey','Vanilla']::text[],'Slowly cooked in small batches so the fruit keeps its character. A spoonful beside a hard or soft cheese is all it needs.','A sweet or sparkling wine','Comte, Brie, goat cheese','Spoon alongside, or warm a little and spoon over baked cheese.','Months, unopened. Keep in the fridge once open.','','{}'::text[],'',10),
('pantry','Preserves and crackers','pantry','Small-batch preserves, crackers and nuts, chosen to sit alongside the cheese.','Any cheese in the collection',5,'',true,'pantry',array['shelves','giftbox']::text[],'Small producers','Contains nuts, gluten','Long shelf life','Crisp, crunchy, sweet',1,array['Crisp','Nutty','Sweet and savoury']::text[],'Preserves, crackers and nuts from small makers, chosen because they make a good cheese better. The selection changes with the seasons.','Ask us, we will find one that suits','Any cheese in the collection','Put a spoonful of preserve beside each cheese, and a few crackers for the table.','Months, unopened. Keep jars in the fridge once open.','','{}'::text[],'',11),
('board-petite','The Petite Board','board','Three cheeses, bread and a preserve on an oak board.','A crisp white',45,'board',false,'gift-petite','{}'::text[],'','','','',1,'{}'::text[],'','','','','','Serves 2 to 4',array['Three cheeses','Bread and crackers','A preserve','On a wooden board']::text[],'',12),
('board-classic','The Classic Board','board','Five cheeses, bread, nuts and a preserve, composed by Benoit.','A light red or white',85,'board',false,'gift-classic','{}'::text[],'','','','',1,'{}'::text[],'','','','','','Serves 4 to 8',array['Five cheeses','Bread, crackers and nuts','A preserve and honey','On a wooden board']::text[],'Most popular',13),
('board-grand','The Grand Board','board','Seven cheeses with bread, fruit, nuts and preserves, for a crowd.','Sparkling and still',150,'board',false,'gift-grand','{}'::text[],'','','','',1,'{}'::text[],'','','','','','Serves 8 to 12',array['Seven cheeses','Bread, fruit and nuts','Preserves and honey','On a large wooden board']::text[],'',14),
('box-tasting','The Tasting Box','box','Three cheeses, crackers and a preserve, wrapped and ribboned.','A glass of something',38,'box',false,'gift-tasting','{}'::text[],'','','','',1,'{}'::text[],'','','','','','A gift for one or two',array['Three cheeses, 100g each','Crackers','A small preserve','Ribbon and handwritten card']::text[],'',15),
('box-evening','The Evening Box','box','Four cheeses, bread, honey and a preserve for a slow evening.','A bottle to share',65,'box',false,'gift-evening','{}'::text[],'','','','',1,'{}'::text[],'','','','','','A gift for two to four',array['Four cheeses','Fresh bread','Honey and a preserve','Ribbon and handwritten card']::text[],'Most popular',16),
('box-hamper','The Hamper','box','A generous mixed hamper of cheeses and pantry goods.','Wine and bread',120,'hamper',false,'gift-hamper','{}'::text[],'','','','',1,'{}'::text[],'','','','','','A generous gift',array['Six cheeses','Bread, crackers and nuts','Preserves and honey','Ribbon and handwritten card']::text[],'',17),
('voucher-25','Gift voucher, £25','voucher','A voucher for the shop, in a black envelope.','Any cheese',25,'voucher',false,'gift-v25','{}'::text[],'','','','',1,'{}'::text[],'','','','','','','{}'::text[],'',18),
('voucher-50','Gift voucher, £50','voucher','A voucher for the shop, in a black envelope.','Any cheese',50,'voucher',false,'gift-v50','{}'::text[],'','','','',1,'{}'::text[],'','','','','','','{}'::text[],'',19),
('voucher-100','Gift voucher, £100','voucher','A voucher for the shop, in a black envelope.','Any cheese',100,'voucher',false,'gift-v100','{}'::text[],'','','','',1,'{}'::text[],'','','','','','','{}'::text[],'',20)
on conflict (id) do update set name=excluded.name, category=excluded.category, note=excluded.note, pair=excluded.pair, price=excluded.price, unit=excluded.unit, price_from=excluded.price_from, img=excluded.img, images=excluded.images, origin=excluded.origin, milk=excluded.milk, age=excluded.age, texture=excluded.texture, intensity=excluded.intensity, notes=excluded.notes, story=excluded.story, drink=excluded.drink, serve_with=excluded.serve_with, serve=excluded.serve, keep=excluded.keep, serves=excluded.serves, includes=excluded.includes, flag=excluded.flag, sort=excluded.sort;
